framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true

    session:
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        cookie_samesite: lax

    router:
        utf8: true

    form: true
    annotations: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
